baseURL = "https://peakwaveoutdoor.com/"
languageCode = "en-us"
title = "PeakWave Outdoor"
theme = "ananke"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # 常用 Ananke 参数，可按需增减
  favicon = "/images/favicon.png"
  description = "Thoughtfully selected outdoor gear."
  github = "https://github.com/outdoor-products/peakwaveoutdoor"
  custom_css = ["custom.css"]
  mainSections = ["gear"]  # 指定主要内容部分
  recent_posts_number = 10  # 显示最近10篇文章

[params.ananke]
  show_recent_posts = true  # 启用最近文章显示

[menu]
  [[menu.main]]
    name = "Products"
    url  = "/gear/"
    weight = 10
  [[menu.main]]
    name = "Events"
    url  = "/event/"
    weight = 20
  [[menu.main]]
    name = "Blog"
    url  = "/post/"
    weight = 25
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 40